### ISSUE TITLE
Global variable is not working.

### ISSUE THREAD

**Issue by sethstha** [livestyle/issues#102]
I am using scss. I have a lot of variables declared in another files. Heard about declaring globals to use variables and mixins. I got my sass folder in my main project folder where is index.html.

i have edited .sublime-project file and added section for globals

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],

    "livestyle":
    {
        "globals":
        [
            "./sass/variables/_colors.scss",
            "./sass/variables/_typography.scss"
        ]
    }
}
```

I don't know what's wrong and why i am not getting variable from colors. I need to @import them every time i need to use variables. Is there anything wrong on my codes.

Thank you

**Comment by sergeche** [comment]
Can you open `background.html` page [as described here](http://livestyle.io/docs/troubleshooting/) and check if there are any errors relates to requested files? Most likely LiveStyle can’t find given files (make sure paths are valid and relative to `.sublime-project` parent folder)

**Comment by sethstha** [comment]
Thank you for the quick response.

I have solved the problem as the color value was having !default in it that was causing the problem. Also i ticked the allow access to file URLs. 

This solved that problems. Thank you for creating this top notch plugin.

**Comment by sergeche** [comment]
thanks! :+1:

**Comment by sethstha** [comment]
And one more thing. You need to save project file inside the project folder itself to make it work.

Thanks
