### ISSUE TITLE
Are there any plans to release as an NPM package?

### ISSUE THREAD

**Issue by jamiewilson** [livestyle/issues#104]
I love the feature set of LiveStyle but would really prefer to use it from the command line. 

I'm also interested in including LiveStyle into a personal development tool/workflow and it'd be awesome to able to install and run it alongside other tools via npm. 

Thanks for creating this nonetheless. It's really cool.

**Comment by sergeche** [comment]
What do you mean by releasing it as npm package? Basically, LiveStyle is a plugin for editor and browser, it doesn’t require any CLI app. Except Remote View feature which requires a background app.

**Comment by jamiewilson** [comment]
Sure. I guess there are a few things that I think could be really useful. I am a big fan of Browsersync and it's [javascript and command line API](https://browsersync.io/docs/api/) along with it's snippet injection option. This makes it possible to:
1. Include Browsersync as a devDependency in my projects (a small static app boilerplate for example) so people can install my boilerplate and get Browsersync automatically. I can handle configuration for them so `npm install` is all they need to do.
2. Automatically inject the browser snippet into my html pages from the build folder so I (and anyone who might use my boilerplate) don't have to add an extension or editor plugin.
3. Utilize the API to call Browsersync programmatically and also pass options (such as enabling/disabling remote view, specifying local ports, ignore changes to certain files, etc).

Hope that helps explain what I meant!

**Comment by sergeche** [comment]
As I said earlier, LiveStyle is a plugin for browser and editor so you can’t include it as a devDependency into npm.

Moreover, the whole idea of LiveStyle is to be build-tool independent: install it once and run everywhere including your live web-site where Browsersync simply not available.

**Comment by jamiewilson** [comment]
Okay. Nevermind then, I guess.
