### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by phdulac** [livestyle/issues#109]
When I make a change in mi file or directly in my browser, nothing happen and i have the following error in my sublime text console :

**UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 26306: ordinal not in range(128)**

**Comment by mui-nyan** [comment]
I also encountered the same error.

**Comment by sergeche** [comment]
There’s something with your CSS, some unicode character that can’t be parsed. Can you post your CSS here?

**Comment by mui-nyan** [comment]
My case.

OK.

```
body{
    background-color: red !important;
}
```

Error. (include japanese character "あ")

```
/* あ */
body{
    background-color: red !important;
}
```

**Comment by phdulac** [comment]
Thank you so muck for your answers. It was a problem with this caracter :  ”
