### ISSUE TITLE
No connected editor

### ISSUE THREAD

**Issue by radojica** [livestyle/issues#110]
Hello!

I really liked older version of live style...and I'm sure I will like new version also but for some reason it is not working!?

LiveStyle app is installed (windows 7) and it is also confirming that chrome and sublime are installed.

 LiveStyle is added manually in latest version of Sublime text 3 because there was no results for "livestyle" inside Package Control.

 LiveStyle extension is also added to latest version of chrome.

http://127.0.0.1:54000/...checked and it is ok

The only problem is that I always get message "No connected editor".

**Comment by sergeche** [comment]
It’s likely you have outdated LiveStyle plugin in ST. Can you restart ST and post here a complete ST console log?

**Comment by radojica** [comment]
Here it is:

`DPI scale: 1.25
startup, version: 3103 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/MiLLeR/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/MiLLeR/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/MiLLeR/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0747772
startup time: 0.103777
first paint time: 0.105777
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Emmet.emmet-plugin
reloading plugin FTPSync.**init**
reloading plugin FTPSync.FTPSync
reloading plugin FTPSync.ftpsynccommon
reloading plugin FTPSync.ftpsyncexceptions
reloading plugin FTPSync.ftpsyncfiles
reloading plugin FTPSync.ftpsyncfilewatcher
reloading plugin FTPSync.ftpsyncprogress
reloading plugin FTPSync.ftpsyncpubsub
reloading plugin FTPSync.ftpsyncworker
reloading plugin FTPSync.ftpsyncwrapper
reloading plugin LiveReload.livereload_st2
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "livereload_st2 in C:\Users\MiLLeR\AppData\Roaming\Sublime Text 3\Installed Packages\LiveReload.sublime-package", line 21
    except Exception, u:
                    ^
SyntaxError: invalid syntax
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin LiveReload.**init**
reloading plugin LiveReload.CoffeescriptPlugin
reloading plugin LiveReload.CommandAPI
reloading plugin LiveReload.CompassPlugin
reloading plugin LiveReload.LESSPlugin
reloading plugin LiveReload.LiveReload
reloading plugin LiveReload.SimpleReloadCallback
reloading plugin LiveReload.SimpleReloadPlugin
reloading plugin LiveReload.SimpleReloadPluginDelay
reloading plugin LiveReload.SimpleWSCallback
reloading plugin LiveStyle.livestyle-plugin
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1519, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\MiLLeR\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\livestyle-plugin.py", line 22, in <module>
    import livestyle.utils.reloader
ImportError: No module named 'livestyle.utils'; livestyle is not a package
reloading plugin SFTP.SFTP
plugins loaded
FTPSync > plugin async loaded
LiveReload: added file /livereload.js with content-type: text/javascript
INFO:WebSocketClient:Starting server
Emmet LiveStyle: Starting LiveStyle server on port 54000
Emmet: No need to update PyV8
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.00ms
Package Control: Skipping automatic upgrade, last run at 2016-02-26 11:35:48, next run at 2016-02-26 12:35:48 or after
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
b'FTPSync > Found no config for {C:\Users\MiLLeR\Desktop\ELANCE\Rachel\bootstrap\css\bootstrap.css}'
b'FTPSync > Found no config for {C:\Users\MiLLeR\Desktop\ELANCE\Rachel\bootstrap\css\bootstrap.css}'
b'FTPSync > Config not found for: C:\Users\MiLLeR\Desktop\ELANCE\Rachel\bootstrap\css\bootstrap.css'
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 1.00ms
`

**Comment by radojica** [comment]
I used this link to download it:
https://github.com/livestyle/sublime-text/archive/master.zip

Link is from this page:
http://livestyle.io/docs/

**Comment by sergeche** [comment]
You have both old (`LiveStyle.livestyle`) and new (`LiveStyle.livestyle-plugin`) plugins so they conflict each other. That’s you couldn’t see LiveStyle in list of packages to install: you already had old plugin.

Try to completely remove LiveStyle plugin and install it again

**Comment by radojica** [comment]
That was the problem...now it works perfectly :+1: 

Thank you for your help.

Are they maybe any plans to make it work with brackets editor?

**Comment by sergeche** [comment]
Yes,  there are plans to add more editors but first I have to fix some critical issues with LiveStyle itself

**Comment by radojica** [comment]
Great...thanks again :+1:
