### ISSUE TITLE
Stuck in "extension is updated"

### ISSUE THREAD

**Issue by smlombardi** [livestyle/issues#116]
I've been successfully using Livestyle for a while, but today when I try to engage it I keep getting this dialog.  I've tried quitting Chrome, Sublime, and Atom.  Nothing works.

![screen shot 2016-04-20 at 9 16 09 am](https://cloud.githubusercontent.com/assets/835148/14675820/c276b8d8-06d8-11e6-9848-a5dcce7b0916.png)

**Comment by sergeche** [comment]
Might be something with Chrome update. Do you see any errors on page’s DevTools console?

**Comment by smlombardi** [comment]
Nope.  I had to open dev tools and reload the page with dev tools open.  Then the next time I clicked livestyle it opened.  Local file (first time I've tried a local file).  

LiveStyle itself is not working; editing css file in Sublime or Atom does not update the page live. Does it not work with `file:///`?

**Comment by sergeche** [comment]
Should work with `file://` but with some limitations doe to Chrome restrictions. It’s better to keep DevTools opened when working with `file://` pages. Maybe Chrome added even more restrictions for `file://` pages recently.

There’s new version of Chrome extension in development, it should be much more stable than current one, but not ETA on release date

**Comment by vinegreet** [comment]
I've got the same problem, with error in console:

> Error in event handler for runtime.onMessage: SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
>     at findStyleSheets (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/content-script.js:1014:12)
>     at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/content-script.js:1052:13

At the background page I get these messages (after refreshing the page):

![image](https://user-images.githubusercontent.com/5248225/37261117-9898f496-25a2-11e8-8071-1fe79a3eca53.png)

**Comment by nroyall** [comment]
I get the same console error and I frequently see the "Extension is updated" message instead of the normal "Enable LiveStyle" message in the Chrome extension panel.

I uninstalled and re-installed the Chrome extension to be sure. 

I'm using SCSS stylesheets and global variables.
