### ISSUE TITLE
What does it mean? not working only with one main.css

### ISSUE THREAD

**Issue by romanbitca** [livestyle/issues#124]
http://prntscr.com/b91ky9

**Comment by sergeche** [comment]
It means your stylesheet has some fancy unicode character which can’t be parsed. Try to find and remove it

**Comment by romanbitca** [comment]
Thank you for quick reply.
Do you have an idea how to find it?, its a 4000lines .css file.

**Comment by sergeche** [comment]
It’s a 69197th character (see log)

**Comment by romanbitca** [comment]
thank you.
I found it. Now it works.
