### ISSUE TITLE
Less Variables Colon

### ISSUE THREAD

**Issue by ParsonsProjects** [livestyle/issues#134]
At the moment livestyle will only pick up variables that have a colon directly after the variable name. For example the below Less var will be picked up when defining it within the CSS.

```
@blue: blue;
body { background: @blue; }
```

Where as the below does not work when there is any number of spaces after the var name and the styles no longer get applied to the site.

```
@blue : blue;
body { background: @blue; }
```

In order to keep the less files in an easy state to read I align all the colon's for vars using aligntab in sublime, however this then breaks livestyle from working correctly. 

Is there any possibility of this working when there is a space between the var name and the colon.

**Comment by sergeche** [comment]
Thanks for detailed report! Just released v0.2.3, this issue should be fixed

**Comment by sergeche** [comment]
UPD: the fix is in Atom plugin

**Comment by ParsonsProjects** [comment]
I tried the Atom plugin but this still had the same issue. Any chance this will be fixed in the sublime plugin?

**Comment by sergeche** [comment]
It’s Chrome extension, actually. Just pushed v1.0.6. should contain this bugfix

**Comment by ParsonsProjects** [comment]
Thanks, that has looked to fix it :)
