### ISSUE TITLE
Turning off on every page reload

### ISSUE THREAD

**Issue by marsspider** [livestyle/issues#138]
i'm using Chrome (_53.0.2785.80 beta (64-bit)_) and every time i reload the page i'm editing LiveStyle turn off.
I remember older versions to "store" pages where LS is enabled so any reload won't turn off extension.

Is it a feature or a bug?? 

Maybe auto-on for previously enabled pages could be an enhancement... 

thnx, Ivan

**Comment by sergeche** [comment]
Should be turned on, but may be turned off if URL of thr page was changed. Can you show me example of your page URL?

**Comment by marsspider** [comment]
i'm in a local webserver... 
the page is the index (single page app) and there are no parameters at all... 

maybe something with blade templating and relative caching??

**Comment by sergeche** [comment]
No, LS caches state by URL (if you say it turned off on reload).
Can check for errors as described [here](http://livestyle.io/docs/troubleshooting/)?

**Comment by marsspider** [comment]
background.js:1231 [DevTools] Loaded stylesheets: []
background.js:1006 send socket message client-id
background.js:1689 Destroy model for http://****_.**_/
_generated_background_page.html:1 Unchecked runtime.lastError while running storage.set: QUOTA_BYTES quota exceeded
    at saveChanges (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/background.js:1886:10)
    at Object.destroy (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/background.js:1693:4)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/background.js:978:19
background.js:1791 set model origin http://****_.**_
background.js:1006 send socket message request-unsaved-changes
background.js:1006 send socket message client-id

maybe is a problem with QUOTA_BYTES exceeded ???

**Comment by sergeche** [comment]
Oh, yeah, it tells that Chrome storage for this plugin is exceeded. Seems like you’re very active LiveStyle user :) Or there’s a bug somewhere. 

Can you try to run `chrome.storage.local.clear()` in console of that background page?

**Comment by marsspider** [comment]
web developer from 1999 ... 
livestyle user from the beginning.. ;)

i'll give a try

**Comment by marsspider** [comment]
Worked! 
this is console output:

chrome.storage.local.clear()
undefined

thnx a lot! 

Ivan
