### ISSUE TITLE
Chrome 54 - QUOTA_BYTES quota exceeded

### ISSUE THREAD

**Issue by mklusak** [livestyle/issues#145]
Hi, there is strange behaviour and I don't know if it caused by my setup or it's some bug. Working on Chrome 54 and Sublime Text 3 (Win 10).

I am locally developing website with fk.loc name. Main page editing works as intended, but not with subpages. LiveStyle icon is green, but no stylesheet is connected. So I choose the correct one, and editor changes are visible in Chrome. But only until first reload. Then the stylesheet is disconnected (= not selected anymore). Extension background page log is attached below.

![livestyle](https://cloud.githubusercontent.com/assets/3023092/20340188/ad818cc0-abe0-11e6-992e-139bfc29314c.jpg)

That error "QUOTA_BYTES quota exceeded" occurs while I choose the stylesheet from list.

When I go to homepage, there is correctly connected stylesheet and everything is fine. But id does not work on subpages. Emmet LiveStyle does not "remember" selected stylesheet.

**Comment by sergeche** [comment]
This error means LiveStyle is unable to save current state since its local storage quota was exceeded. Try to open LiveStyle background page [as described here](http://livestyle.io/docs/troubleshooting/#getting-debug-data) and run

```
chrome.storage.local.clear()
```

in page’s console. It will clear all stored LiveStyle data so it will be able to save data again

**Comment by mklusak** [comment]
Heureka! It works, thank you very much!

It's some "per extension" quota? Or "per domain name" quota?

**Comment by sergeche** [comment]
It’s a per-extension quota. Maybe I’ll be able to optimize it somehow, but for now this project is on-hold for me due to low community interest

**Comment by mklusak** [comment]
Ok. Thank you for you work!
