### ISSUE TITLE
Livestyle No Longer Detecting Chrome Extension

### ISSUE THREAD

**Issue by txh120530** [livestyle/issues#149]
If what the extension page is anything to go by, the Livestyle extension was updated today. No idea if that's what's causing the issue or not but it was working perfectly fine this morning then suddenly nothing was updating. I tried everything I thought to do, restarting livestyle, Chrome, my computer, and everything in the troubleshooting page but it's still not detecting the extension. It does seem to sometimes work editor to browser but not at all the other way.

![615d05a8f1f9cf734f77d8323e46d763](https://cloud.githubusercontent.com/assets/9092836/23868407/47f0f594-07ed-11e7-9c45-70d6b30f8f47.png)

![2ddc44f5628c8626f22efd6027a61336](https://cloud.githubusercontent.com/assets/9092836/23868415/4e7c62e0-07ed-11e7-9f07-b60fb3c668ac.png)

**Comment by sergeche** [comment]
It might happen if, for some reason, Chrome installed extension into another folder, not currently supported by LiveStyle app. It’s not a problem since Chrome extension is already installed.

**Comment by sergeche** [comment]
Uploaded v1.0.8 that fixes live editing into Chrome Web Store, should be available shortly.
