### ISSUE TITLE
LiveStyle not detecting changes

### ISSUE THREAD

**Issue by heyfella** [livestyle/issues#150]
Was using LiveStyle last week and it was working fine. It's stopped working now. If I edit in Chrome nothing happens in Sublime text. I have tried the following;
 - set to bi-directional updates and have also tried just browser to editor. 
 - Have removed and installed extension
 - Removed and installed Sublime Text
 - Restarted Chrome and Sublime (and rebooted)
Nothing seems to work.

I'm using Mac OSX 10.12.3
Chrome Version 57.0.2987.98

Anyone got any thoughts?

**Comment by sergeche** [comment]
Can you post a `background.html` console log here?

**Comment by tsymbal** [comment]
Та же беда. Со вчерашнего дня перестал работать плагин. Ни в одну сторону, ни в другую. Windows 8, chrome последний, sublime 3. Работа "встала" :( 
В консоли нет никаких записей об ошибках. Очень жду обновлений...

**Comment by sergeche** [comment]
На самом деле никаких изменений не было, просто добавлен фоновый скрипт трэкинга. Что показывает попап с LiveStyle?

**Comment by sergeche** [comment]
Does it works with example described here? http://livestyle.io/docs/using-livestyle/

**Comment by tsymbal** [comment]
http://joxi.ru/Dr897ENc4ynQBm - в попапе всё хорошо. никаких ошибок. 
http://joxi.ru/E2pnxgbu9YVnBr - здесь тоже. 
Пробовал перезагружать компьютер.

**Comment by tsymbal** [comment]
Переустановил App, все плагины. Никаких изменений. На любых сайтах, с любыми файлами css. Ох беда,.. как не вовремя... :( Всё-таки грешу, что, может быть, это только у меня. Буду пробовать найти решение. Если получится, отпишусь.

**Comment by tsymbal** [comment]
Работает только в одну сторону: из Sublime в Chrome. В обратную не работает, к сожалению.

**Comment by heyfella** [comment]
no it doesn't work with the example on http://livestyle.io/docs/using-livestyle/. This is the background log when I tried to work with the example files.
[background_log.txt](https://github.com/livestyle/issues/files/841119/background_log.txt)

**Comment by fullgod** [comment]
Может откатиться до стабильной версии? Вы не могли бы сообщить ссылку на стабильную версию плагинов?

**Comment by sergeche** [comment]
How to revert to previous version:

1. Remove currently installed LiveStyle extension
2. Download and unpack [LiveStyle 1.0.6](https://github.com/livestyle/issues/files/841288/livestyle.zip)
3. In Chrome, go to Extension page and check “Developer mode” in upper right corner of the page
4. Hit “Load unpacked extension...” button and pick folder with unpacked LiveStyle 1.0.6

Let me know if it fixes issue for you

**Comment by valeenGLX** [comment]
Откатив до LiveStyle 1.0.6 работает! Спасибо Вам большое!

**Comment by tsymbal** [comment]
Да, тоже работает. Откатил по инструкции. Урраааа! Всем спасибо. 

Сергей, вам, несмотря ни на что, огромный респект за LiveStyle! Я уже просто не представляю свою жизнь без этого плагина.

**Comment by sergeche** [comment]
Хм, странно, неужели трэкер сломал так? Сейчас тогда откачу опубликованную версию и буду разбираться

**Comment by sergeche** [comment]
Ой, по ошибке удалил нужные данные 🙈 можете проверить [эту сборку](https://github.com/livestyle/issues/files/841478/livestyle.zip)? если всё работает, закину её в стор расширений

**Comment by tsymbal** [comment]
да [эта сборка](https://github.com/livestyle/issues/files/841478/livestyle.zip) работает! Спасибо!

**Comment by sergeche** [comment]
Uploaded v1.0.8 into Chrome Web Store, should be available shortly.

**Comment by sergeche** [comment]
Кстати, мне было бы интересно получить фидбэк по LiveStyle: как он используется, для решения каких задач, чего хотелось бы улучшить. В ветке есть сильно улучшенная и более надёжная (но не протестированная версия), все работы по проекту я пока заморозил, потому что низкий интерес к нему и есть очевидные проблемы с UX. Можно написать фидбэк на serge.che@gmail.com

**Comment by fullgod** [comment]
Да вы что. Проект просто незаменим в верстке. В связке с PerfectPixel. Экономит уйму времени.

**Comment by heyfella** [comment]
v1.0.8 has fixed my problem. 

Re LiveStyle I have only been using it for a week but can't imagine working without it now. Awesome extension good work. Have already recommended it to 3 other developers.
