### ISSUE TITLE
Livestyle only working editor -> browser

### ISSUE THREAD

**Issue by ArgentiAertheri** [livestyle/issues#151]
After restarting, uninstalling any and all of: chrome, sublime, and livestyle; and going through everything both on the main troubleshooting page and here, I give up, I need help.

If I edit the css in sublime, the changes show in chrome. The reverse is not true, even on the [demo page](http://livestyle.io/docs/using-livestyle/).

This is all that shows on the background page's console:

> send socket message client-id
> background.js:1791 set model origin http://livestyle.io
> background.js:1006 send socket message client-id

And the sublime console:

> startup, version: 3126 osx x64 channel: stable
> executable: /Volumes/Gaia/Applications/Sublime Text.app/Contents/MacOS/Sublime Text
> working dir: /
> packages path: /Users/Argenti/Library/Application Support/Sublime Text 3/Packages
> state path: /Users/Argenti/Library/Application Support/Sublime Text 3/Local
> zip path: /Volumes/Gaia/Applications/Sublime Text.app/Contents/MacOS/Packages
> zip path: /Users/Argenti/Library/Application Support/Sublime Text 3/Installed Packages
> ignored_packages: ["Vintage"]
> pre session restore time: 1.2037
> first paint time: 1.49135
> startup time: 1.49648
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin LiveStyle.livestyle-plugin
> plugins loaded
> LiveStyle: Start app
> LiveStyle: Client connected

I'm running sublime 3, chrome downloaded a couple hours ago while troubleshooting, on OSX El Capitan, and I've got a handy little app to ensure that when I delete things, all associated files get deleted too -- no lingering settings. Basically, I have no idea wtf is going on, other than that the computer gods are apparently saying "blizzard means you don't work"!

Edit: Just double checked, and nope, running the demo page completely outside MAMP doesn't effect anything. So MAMP is off the list of potential problems now too.

**Comment by sergeche** [comment]
Uploaded v1.0.8 into Chrome Web Store, should be available shortly.
