### ISSUE TITLE
@import

### ISSUE THREAD

**Issue by derekoakley** [livestyle/issues#17]
I have a file which uses @import to load the component scss files.

If I make a change in the component scss nothing happens.

If I choose the component scss file in the livestyle browser extension then the change naturally appears instantly in the browser.

Is there a way to not have to choose said component scss file in order for the change to appear?

**Comment by sergeche** [comment]
You have to associate your component with existing stylesheet in browser (or create new one via “Add stylesheet”). Otherwise LIveStyle doesn’t know which stylesheet should receive changes

**Comment by derekoakley** [comment]
Thank you for the quick response! I guess this is the difference between livestyle's and takana's implementation.

**Comment by sergeche** [comment]
Yes. Unlike with other live reload tools, you don’t have to save files and you can update stylesheets in both directions (from browser to editor too)
