### ISSUE TITLE
Detect syntax from file name

### ISSUE THREAD

**Issue by Priler** [livestyle/issues#18]
I'm using:
Emmet LiveStyle 0.9 Alpha + Windows 7 + Chrome 41.0.2272.101 + Sublime Text 3.

Simple .css editing is works fine, but it's useless without less.
When I'm trying to connect .less file and write something like:
@base:#FF0000;
body {
    background:@base;
}

It's not works.
And if i try to put #FF0000 in case of @base to body->background rule in my .less file it will work.
So, in case of writed above i can say that less preprocessing is not works for me.

**Comment by sergeche** [comment]
Did you set document to LESS? Can you post a screenshot of your editor and LiveStyle file associations?

**Comment by Priler** [comment]
index.html : http://prntscr.com/6o55f8
browser window : http://prntscr.com/6o5620
styles.less file : http://prntscr.com/6o564q

**Comment by Priler** [comment]
it's also gives this in debug console : http://prntscr.com/6o56pd

**Comment by sergeche** [comment]
From your editor screenshot I can tell your syntax is set to CSS, not LESS

**Comment by Priler** [comment]
View->Syntax in my Sublime Text set to CSS, is that a problem?

**Comment by sergeche** [comment]
Yes, exactly

**Comment by Priler** [comment]
But there is no Less syntax in my Sublime Text, how can i fix it?

**Comment by sergeche** [comment]
Install it via Package Control: 
https://packagecontrol.io/installation
https://github.com/danro/LESS-sublime

**Comment by Priler** [comment]
It works now :)
Thanks a lot.

I think you got to mansion this in your article about Alpha 0.9 here http://livestyle.emmet.io/alpha/

**Comment by sergeche** [comment]
You made a good case of using different syntax for document :) Current implementation looks on document syntax only (e.g. you can even create an untitled file and use it for live edit; you don’t have to save it). I think I should also check for file extension for such cases

**Comment by Priler** [comment]
Of course i did, logicaly it would be better to create check queue for less detecting.
1. With file ext
2. With syntax

Or you can add some sort of parameter in extension box within Chrome to make LiveStyle focibly interpretate file as less.

Well, thanks for helping, im happy now :)
