### ISSUE TITLE
Puzzeled

### ISSUE THREAD

**Issue by CarlosMed** [livestyle/issues#19]
Hello I was wondering if livestyle has a way of updating locally like lets say on my iphone safari browser when changes are made?

**Comment by sergeche** [comment]
See “Generic browser client” section: http://livestyle.emmet.io/alpha/

**Comment by CarlosMed** [comment]
Sorry I tried that already but couldn't get it to function on my mobile phone.

**Comment by sergeche** [comment]
Please be more specific on what exactly you and how you’ve tried to test it

**Comment by CarlosMed** [comment]
OK well it says to put the script tag into the html, replacing the IP with my IP, and navigating to that IP address in the browser. I then proceed to type it into mobile Safari on my phone but it doesn't seem to work using my ip address and while having MAMP on or off. So im not sure how to get it to work on my phone to view the changes automatically. Is it even possible to see automatic changes on a mobile phone browser? Sorry if im not making much sense kinda hard to explain it.

**Comment by sergeche** [comment]
Can you provide some screenshots of your page HTML and console output from your mobile web-page?

**Comment by CarlosMed** [comment]
How do i show console output on my mobile phone?

**Comment by sergeche** [comment]
What’s your mobile phone model?

**Comment by CarlosMed** [comment]
IPhone 6+

**Comment by sergeche** [comment]
http://www.smashingmagazine.com/2014/09/03/testing-mobile-emulators-simulators-remote-debugging/2/

**Comment by sergeche** [comment]
Closing due to lack of required information. Please re-open this issue if you going to publish some screenshots I asked.
