### ISSUE TITLE
Stop littering console

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#25]
![console](https://cloud.githubusercontent.com/assets/93595/7410013/caa65800-ef33-11e4-8ca4-a10dd50ff691.png)

**Comment by paulirish** [comment]
Chrome had invalid CSS warnings but the false positives were so all over the place that we had to remove it. 
IMO this is a bug for the devtools.

**Comment by sergeche** [comment]
No, it’s actually messages from my CSS expression parser: it treats all standard CSS functions and keywords as variables and shows warnings if it can’t find variable definitions in current scope :)

**Comment by paulirish** [comment]
ooohhhhh gotcha
