### ISSUE TITLE
Failed to parse the &.sibling_node

### ISSUE THREAD

**Issue by ianberdin** [livestyle/issues#3]
http://take.ms/cM95u
LiveStyle: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.p-lessons .p-lessons_cnt . .p-lessons_cnt_i.__disabled {}'.

https://gist.github.com/happierall/5c5b5558cd83e3c8e692

**Comment by sergeche** [comment]
А где определяются переменные? У меня этот пример нормально отработал.

Если убрать все миксины и переменные — работает?

**Comment by ianberdin** [comment]
Странно, теперь вроде все работает. Закрываю.
