### ISSUE TITLE
Tornado.access:404 in Sublime Text 3 console log

### ISSUE THREAD

**Issue by WesleySmits** [livestyle/issues#30]
I'm getting the following error: WARNING:tornado.access:404 GET /livestyle (127.0.0.1) 0.37ms

For the record, this only happens in the 0.9 alpha version. The 0.8 version works perfectly (Except for the lack of .scss support).

**Comment by sergeche** [comment]
It looks like you didn’t updated ST plugin (or didn’t removed old one), as described here: http://livestyle.emmet.io/alpha/

**Comment by Xample** [comment]
I had the same issue, I just ran "Package Control: Remove package" > "LiveStyle" and then "Package Control: Install package" > "LiveStyle". Restarted Sublime Text and now it works
