### ISSUE TITLE
"Write Protection" issue after downloading zip file link.

### ISSUE THREAD

**Issue by robocato1** [livestyle/issues#33]
I was on page "http://livestyle.emmet.io/alpha/" and was given a zip download(below) for downloading zip package for the 'Sublime Text Extension'. 

```
"Sublime Text extension
Current plugin was tested in Sublime Text 3 and may not work in Sublime Text 2.

In Sublime Text, pick Preference > Browse Packages... menu item to open Packages folder.
Create LiveStyle folder in it
Download package ZIP and extract its contents into a newly created LiveStyle folder.
Restart Sublime Text.
You can also checkout git repo to get automatic updates if your have Package Control installed."
```

I was prompted to make sure to delete previous versions of "LiveStyle" on Sublime Text (I use ST2) and delete the chrome extension completely before downloading this new Sublime Text Extension for "LiveStyle Alpha" package. 

I did that. I had no issues uninstall and deleting sublime text "LiveStyle" package and the chrome extension for developer's tools "Emmet LiveStyle" package. 

I noticed in the Sublime "Packages" folder that the "LiveStyle" folder was still there, so I deleted it completely. Then I downloaded the new package for "LiveStyle Alpha". I was able to download the zip, then extract the files from the zip into the same folder, which was a new folder I named "LiveStyle" under the sublime "packages" directory. When I tried to delete the master-zip that's when I started having the issues with "write protection". Now I cannot delete or modify anything. It's on my computer thumbdrive. It doesn't even give me the option to delete most files in my thumb or computer. 

I tried fixing the "read-only" options, but everything says it is already an unchecked option. 

I was using Sublime Text 2 on Windows 64-bit OS and Google Chrome. I have simple packages in Sublime installed like "Predawn, LoremGibson, BracketGuard, Emmet, ColorSchemeSelector, SublimeWebColors".

**Comment by sergeche** [comment]
You should check/fix file permissions on your system. Downloaded zip can’t cause any write protection error, but something on your system
