### ISSUE TITLE
Refresh doesn't pick up styles

### ISSUE THREAD

**Issue by rob-mcdonald** [livestyle/issues#37]
It seems you start from scratch on a hard refresh (but weirdly, it seems [some classes are cached but not quite properly](#after-hard-refresh)). There's some issues I'm seeing when testing basic CSS.

I'd ask for a feature request to pick up the initial state of the `less` files on hard refresh. It's going to be quite time consuming to comment out or retype the `@variables` and styles to get it back to the old state. I'll be testing a localhost site with a `main.css` file compiled with Gulp so perhaps that'll work better.

**Basic styles**

``` less
// @import 'variables.less'

@variable: blue;
@color: pink;
@text-color: #fff;

html {
  background: @color;
  background: @variable;
}
h1 {
  color: @color;
}
.wrapper {
  background: black;
  border: 1px solid black;
  color: blue;
  p {
    color: @text-color;
  }
}
```
#### After hard refresh:

I don't even think this should have any styles at all! I don't have the log for this as I wanted to clear the console to just display recent events. I haven't been able to replicate this yet. It could be the caching issue I was having with a global `variables.less` file (which I disabled and tried to `@import` instead).
![screen shot 2015-08-10 at 10 50 23](https://cloud.githubusercontent.com/assets/13622137/9167854/a4671822-3f4d-11e5-90fc-c55212bd213f.png)

**Should be like:**
![screen shot 2015-08-10 at 11 10 49](https://cloud.githubusercontent.com/assets/13622137/9169272/9f9753b6-3f52-11e5-94fb-0c2057614bb1.png)

**Also:**
- `background` order is not respected (might be [wrong diff order issue](https://github.com/livestyle/issues/issues/35))
- Commenting out doesn't work properly `// background: @variable;` turns the background white)
- Have to `cmd + //` both `backgrounds` and reinstate a single one for it to display properly
- Commenting out `.wrapper { color: blue; }` flashes the `background: black` but it doesn't stay black

**Comment by sergeche** [comment]
> I'd ask for a feature request to pick up the initial state of the less files on hard refresh.

You mean do no apply unsaved changes in editor file on page refresh?

**Comment by rob-mcdonald** [comment]
No I mean apply whatever is in the saved (mapped) files or unsaved changes on refresh. If it's possible ;)

**Comment by sergeche** [comment]
Hmm, all unsaved changes on mapped files must be applied on refresh. Might be a bug

**Comment by rob-mcdonald** [comment]
Ok, I've had it work if I've built file from scratch, but not quite properly. When opening Sublime again and clearing console it starts from scratch (which is likely expected). Is there a specific process other than: close tab > open new tab > navigate to `file:///` > open dev tools? I might be making some rookie mistakes.

**Comment by rob-mcdonald** [comment]
Also, is it unwise to have Gulp task running while using the plugin?

**Comment by sergeche** [comment]
If your Gulp task automatically refreshes CSS in opened page, it may lead to errors, especially if you have DevTools opened.

**Comment by rob-mcdonald** [comment]
Yep, that's what it's doing. Ok I'll try it out without the Gulp task, but LiveStyle might not play well with some of the javascript components — I'll add an issue if this is true.

**Comment by rob-mcdonald** [comment]
Another thing to note is it would be nice to see changes reflected even if LiveStyle is turned off. I can make do for now without seeing changes reflected when adding newly mapped files (although that would be helpful) — but if:

- File has been mapped
- Switch Livestyle off
- Make changes to file (possibly save)
- Turn Livestyle on again

The new changes should be reflected? The issue is if you switch it off (for whatever reason) and using this as an example (which is overriding some existing `border` styles):

*1: LiveStyle switched on and `border: none;` added*

```less
.btn-register {
  .secondary-btn;

  border: none;

  &:hover {
    border: none;
  }
}
```

*2: switch off and make changes:*

```less
.btn-register {
  .secondary-btn;

  // border: none;

  &:hover {
    // border: none;
  }
}
```

Now, switch back on again. The changes aren't reflected but also, even if you remove the styles completely, it doesn't return to it's previous state (1). You'd have to add the `border` css we're trying to override in the first place to see the same styles that `main.css` has.

Using editor -> browser [Log](http://codeshare.io/35Cc7)

**Comment by sergeche** [comment]
> Another thing to note is it would be nice to see changes reflected even if LiveStyle is turned off

It’s better to have it as separate issue

**Comment by rob-mcdonald** [comment]
Ok, no problem ;)

**Comment by sergeche** [comment]
This issue is still relevant?
