### ISSUE TITLE
Parse the "Global" mixins files from @import.

### ISSUE THREAD

**Issue by ianberdin** [livestyle/issues#4]
Ведь можно парсить путь из @import и добавлять эти пути?
А то прописывать ручками в большом проекте - жуть.
Я например все @import пишу только в одном файле - этого хватает. (Который компилирую)
Да сделать парсер думаю будет проще.

П.С. хотя разница-то: пройти по всем файлам (.less) и собрать все @import или взять в одном - почти никакой.

Будет здорово, если реализуете.

**Comment by sergeche** [comment]
Вообще так и должно работать? В global можно указать путь к файлу, который содержит коллекцию импортов и все они должны подгрузиться и давать свои переменные и миксины. По крайней мере у меня по юнит-тестам всё работает. Может, пути неправильные указаны? В `background.html` по-моему должен выводиться лог запрашиваемых зависимостей

**Comment by ianberdin** [comment]
Нее, я имел ввиду: не прописывая в Global.

**Comment by ianberdin** [comment]
Оффтоп:
Кстати, к sublime сильная привязка?
Насколько трудно будет перенести в другой редактор? Например WebStorm?

**Comment by sergeche** [comment]
Теоретически можно, но могут возникнуть проблемы с производительностью и с перекрытием переменных и миксинов. Особенно опасно с миксинами, так как они не перекрываются, а добавляются в коллекцию и выводятся все, которые соответствуют названию.

К редактору привязка минимальная, по сути он должен уметь только поднимать сокет-сервер и и сообщать об изменениях в текстовом буффере. В дальнейшем планируется поддержка большего количества редакторов.

**Comment by ianberdin** [comment]
Понял, благодарю.
