### ISSUE TITLE
Inspect element gets stuck

### ISSUE THREAD

**Issue by rob-mcdonald** [livestyle/issues#42]
Sometimes gets stuck on a specific element and you have to close/reopen the inspector. Not sure if this log will help at all: http://codeshare.io/zyKoP

**Comment by sergeche** [comment]
LiveStyle does not affect DevTools

**Comment by rob-mcdonald** [comment]
Oh. Well I have no idea why it would be getting stuck on an element then. Perhaps it's a Chrome issue.
