### ISSUE TITLE
Изменение аргументов миксинов без патчинга

### ISSUE THREAD

**Issue by ianberdin** [livestyle/issues#5]
Если в less: .border-radius(5px); (mixin)
Сейчас, если поменять в браузере параметр border-radius: 6px;
То, в редакторе добавляются дополнительные строки с border-radius: 6px;

Хотелось бы, чтобы просто правились аргументы.

**Comment by sergeche** [comment]
Да, это есть у меня в планах, но в общем виде это довольно сложно решается. Потому передаваемые аргументы могут применяться в разных выражениях внутри миксина и не факт что миксин сгенерирует только одно свойство.
