### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#53]
Missing interpolation:

```
max-width: #{$fullwidth}px;
------------^
```

Different `rgba()` function signature: `rgba(white, .8);`

```
Cannot read property 'unit' of undefined
```

**Comment by enoversum** [comment]
If this is of any help, the second error is coming from a function from an imported scss file:

```
@function white($opacity){
    @return rgba(255,255,255,$opacity)
}
```

The first one is a variable right from the same scss document.

**Comment by sergeche** [comment]
No, it’s `rgba()` function that expects 4 arguments: https://github.com/livestyle/css-expression/blob/master/lib/functions.js#L191

`white` is a standard CSS color keyword here, not a function.

**Comment by enoversum** [comment]
Yeah, well, of course! My bad, of course! The function is not involved ;).
However, SASS interprets the colour names when compiling and spits out the four argument version, so it at least works for SASS itself.
