### ISSUE TITLE
Проблема с настройкой 

### ISSUE THREAD

**Issue by Zet-Web** [livestyle/issues#57]
Добрый день ...  Никак не могу настроить плагин для корректной работы... 
Он у меня работает раз через раз ... 
Сейчас вообще кликая по окошку в списке расширений хрома ничего не происходит ...  В самом редакторе следующая ошибка WARNING:process:Could not import subprocess32 module, falling back to subprocess module

**Comment by sergeche** [comment]
Какая ОС? Какая версия Sublime Text, Chrome? По какому окошку кликаете?

**Comment by Zet-Web** [comment]
Windows 10 , Sublime text 3 ...  В принципе проблема относительна решилась, но в консоли всё равно частенько ругается на subprocess32 module ... И время от времени все таки крашится браузерный модуль, точнее расширение... Но кстати это происходит тогда, когда открыто два окна хрома...

**Comment by sergeche** [comment]
А в чём проявляется крэш расширения?

**Comment by Zet-Web** [comment]
Оно перестаёт быть кликабельным...  кликаешь по нему , но окошко не появляется... Переходишь в режим дебаггинга приложения. там выдаёт ошибку...  Окошко просто перестаёт быть кликабельным...  Возможно есть какие то плагины у Sublime . которые конфликтуют с LiveStyle Alpha.... Сейчас допустим опять же на домашнем PC перестал работать, т.е выдаёт ошибку о том, что порт закрыт и что то блокирует его ... Много вопросов если честно связанных с этим чудесным плагином, замены ей нету на сегодня, но вот до идеала её довести мне никак не удаётся. То , что он правит sass в режиме реального времени это мега-фича... Но кстати порой не хватает возможности посмотреть внесенные стили, возможности откатить какой либо из них ... То, что есть в PHPStorm - в связке в css-x-fire. И мануал на русском тоже не помешал бы хоть какой нибудь, именно от вас, как документация...

**Comment by sergeche** [comment]
А какая у вас сейчас версия расширения для Chrome?
То, что закрыт порт — это частая ошибка при нормальной работе. Но ещё это может означать, что не работает сервер в редакторе. Можете запостить полный лог из консоли ST3? И список всех плагинов, которые установлены в ST?

> Но кстати порой не хватает возможности посмотреть внесенные стили, возможности откатить какой либо из них ...

Обычно это делается через версионный контроль. Предпросмотр изменений требует отдельного UI, который ещё нужно продумывать и не факт, что он будет востребован.

**Comment by sergeche** [comment]
Эта проблема ещё актуальна?
