### ISSUE TITLE
error during websocket handshake

### ISSUE THREAD

**Issue by littlegreenguy** [livestyle/issues#61]
Hi, I'm running sublime text 3 and have installed the livestyle extension as instructed in chrome and ST3. When I click on the chrome extension I get: "no connected editor".

chrome log:

background.js:885 [DevTools] Received message Object {name: "get-stylesheets"}
background.js:885 [DevTools] Received message Object {name: "reset"}
background.js:885 [DevTools] Loaded stylesheets: []
background.js:885 [DevTools] Received message Object {name: "reset"}
background.js:885 [DevTools] Loaded stylesheets: []
background.js:2933 WebSocket connection to 'ws://127.0.0.1:54000/livestyle' failed: Error during WebSocket handshake: Unexpected response code: 404
background.js:1344 Destroy model for http://meraki.dev/
background.js:885 [DevTools] Received message Object {name: "get-stylesheets"}
background.js:2933 WebSocket connection to 'ws://127.0.0.1:54000/livestyle' failed: Error during WebSocket handshake: Unexpected response code: 404
background.js:885 [DevTools] Received message Object {name: "get-stylesheets"}
13background.js:2933 WebSocket connection to 'ws://127.0.0.1:54000/livestyle' failed: Error during WebSocket handshake: Unexpected response code: 404

ST3 console:
reloading plugin LiveStyle.livestyle
reloading plugin emmet-sublime-master.emmet-plugin
plugins loaded
Initializing 1self plugin
Emmet LiveStyle: Starting LiveStyle server on port 54000
Emmet: No need to update PyV8

Hope you can help - Many thanks!

Nick

**Comment by sergeche** [comment]
It looks like you’ve installed old (current) plugin for Sublime Text. You should remove it and install new (alpha) version as described here: http://livestyle.io/docs/#manual-installation-of-sublime-text-plugin

**Comment by littlegreenguy** [comment]
Hi Sergey,

Thanks for getting back to me…

I deleted the files in that folder and downloaded them fresh but still get the same issue..

WebSocket connection to 'ws://127.0.0.1:54000/livestyle' failed: Error during WebSocket handshake: Unexpected response code: 404

Files:

The link for the download is: https://github.com/livestyle/sublime-text/archive/master.zip

Many thanks,

Nick

**Comment by sergeche** [comment]
Can you show me a full console log from ST when start editor?

**Comment by littlegreenguy** [comment]
here it is:

startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/nickalexander/Library/Application Support/Sublime Text 3/Packages
state path: /Users/nickalexander/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/nickalexander/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Emmet", "jQuery", "jQuery Snippets pack", "Vintage"]
pre session restore time: 0.235567
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
startup time: 0.309772
first paint time: 0.360097
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 1Self.1self
reloading plugin 1Self.1selfOpenDashboardCommand
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Blade Spacer.BladeSpacer
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin DocBlockr.jsdocs
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin Phpcs.phpcs
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin emmet-sublime-master.emmet-plugin
reloading plugin LiveStyle.livestyle-plugin
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1519, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/nickalexander/Library/Application Support/Sublime Text 3/Packages/LiveStyle/livestyle-plugin.py", line 22, in <module>
    import livestyle.utils.reloader
ImportError: No module named 'livestyle.utils'; livestyle is not a package
plugins loaded
Initializing 1self plugin
Emmet LiveStyle: Starting LiveStyle server on port 54000
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-11-02 15:48:55, next run at 2015-11-02 16:48:55 or after

Thanks,

Nick

**Comment by sergeche** [comment]
> reloading plugin LiveStyle.livestyle
> reloading plugin LiveStyle.livestyle-plugin

You still have old LiveStyle plugin installed. Check out both `~/Application Support/Sublime Text 3/Packages` and `~/Application Support/Sublime Text 3/Installed Packages` folder and remove any traces of LiveStyle extension that do a fresh manual LiveStyle install

**Comment by littlegreenguy** [comment]
Perfect!! thanks so much! Sublime was adding back the old plugin automatically through package control… so as quick as I was deleting them, it was adding them back! Deleted through package control, manual installed as you instructed… bingo!

I really loved using the previous version - you have really revolutionised my workflow, what you’ve done with this version looks awesome!

I’m not very rich, but would like to send a donation/random gift of curiosity! Have you got facility for this?

Many thanks,

Nick

**Comment by sergeche** [comment]
Thanks for your kind word :) I’m going to start a crowdfunding campaign after LiveStyle release for further development so you can have a chance to support it. Stay tuned for updates at my [twitter account](https://twitter.com/emmetio)

**Comment by littlegreenguy** [comment]
perfect - will do. many thanks again!
