### ISSUE TITLE
SCSS variable bug

### ISSUE THREAD

**Issue by iv-retriever** [livestyle/issues#7]
Hello, I'm Korean Dev(my english short)

I had some problem.

If I make var in .scss like this $a: 100px; and change the css in chrome devtool, So first change is good to work.

But second, third, ... change make wrong value. 

This case is appeared only when I change value sequentially in chrome devtool.

ex)

$a: 100px;
body{
   margin-top:$a;
}
1. First change
   Chrome: body{ margin-top:100px} --> body{ margin-top:50px} / ST: margin-top:$a - 50px; (good work)
2. Second change 
   Chrome: body{ margin-top:50px} --> body{ margin-top:10px} / ST: margin-top:$a + 10px; (wrong calc, correct calc is $a - 90px)

**Comment by sergeche** [comment]
Fixed, please update both Chrome and Sublime Text extensions
