### ISSUE TITLE
Fail after update 1.0

### ISSUE THREAD

**Issue by frontalex** [livestyle/issues#72]
I upgrade extension and plugin. After this, if i click on yet another new button - "No connected editor".

**Comment by sergeche** [comment]
Please make sure you have the most recent Sublime Text plugin as well

**Comment by frontalex** [comment]
Restarting OS help me fix this problem. Now extension can activated and work, but local files stay not editable, - css not attaching, and button "add stylesheet" not clickable.

**Comment by sergeche** [comment]
Hmm, can you try to remove and install LiveStyle extension in Chrome? Also, there’s a guide how to debug problems: http://livestyle.io/docs/troubleshooting/
Check out DevTools console for possible error reports, as well as `background.html` page log

**Comment by frontalex** [comment]
![untitled](https://cloud.githubusercontent.com/assets/435920/12017841/e15ed2b4-ad85-11e5-9a24-f57aa4a30cbf.png)

**Comment by frontalex** [comment]
![untitled](https://cloud.githubusercontent.com/assets/435920/12018201/46d4e544-ad8a-11e5-9775-2ca26986642b.png)

**Comment by sergeche** [comment]
Я так понимаю, проблема была с локальным файлом (протокол `file://`)?

**Comment by frontalex** [comment]
Ага. С утра сегодня опять css не находил, помогла переустановка расширения.

**Comment by sergeche** [comment]
Такое бывает после автообновления расширения и эта ситуация описана тут: http://livestyle.io/docs/troubleshooting/#empty-list-of-stylesheets
Нужно закрыть DevTools и просто обновить страницу
