### ISSUE TITLE
windows 8 : installation unknown and failed

### ISSUE THREAD

**Issue by eissasoubhi** [livestyle/issues#73]
Windows 8 protection prevent the desktop application to be installed as an uknown application.

after unblocking it in app properties . the installation failed in the first time

**Comment by sergeche** [comment]
AFAIK you saw a SmartScreen protection (big block across entire screen)? Unfortunatelly, I can’t affect it right now, users has to explicitly allow app installation.

Anyway, did app installed correctly afterwards or you received errors?

**Comment by eissasoubhi** [comment]
yes, it installed now but at first when i tried to install it. it showed me a small window (something like snake game window). 
Unfortunately it's not working and keeps showing this error "No connected editor" every time i click the LiveStyle icon in browser toolbar.
i checked everything  : i have the most recent version of Sublime Text package "2015.12.28.22.44.34" .
My LiveStyle websockets server is up and running

**Comment by sergeche** [comment]
>  it showed me a small window (something like snake game window)

it’s installation progress window

> Unfortunately it's not working and keeps showing this error "No connected editor" every time i click the LiveStyle icon in browser toolbar.

try to visit http://127.0.0.1:54000, what message do you see? I need exact message phrase

**Comment by eissasoubhi** [comment]
i see LiveStyle websockets server is up and running

**Comment by sergeche** [comment]
It’s a message from old plugin. Looks like it wasn’t updated. Can you remove LiveStyle plugin from ST and install it again?

**Comment by eissasoubhi** [comment]
it's working now THANK YOU :+1:

**Comment by sergeche** [comment]
Great! One more thing: do you remember what app displayed for Sublime Text after you installed it? It should automatically upgrade old plugin and show `Installed` label. Looks like something went wrong and it didn’t upgrade plugin

**Comment by eissasoubhi** [comment]
it just installed normally as all Sublime Text plugins do. but before i removed it and installed it again.  i updated it with Sublime Text command "upgrade package" but it didnt work.
