### ISSUE TITLE
Livestyle doesn't work locally

### ISSUE THREAD

**Issue by MaxdeMooij** [livestyle/issues#75]
On every live website, I can edit the stylesheets. But when working on a local HTML file (with local stylesheets), Livestyle can't find nor add any stylesheets. 

The instructions on http://livestyle.io/docs/troubleshooting/#empty-list-of-stylesheets don't seem to solve the problem.

**Comment by sergeche** [comment]
Try to open Preferences > Extension and enable “Allow access to file URLs” checkbox in LiveStyle plugin

**Comment by MaxdeMooij** [comment]
Thanks, that worked! Couldn't find it anywhere on the website.

**Comment by sergeche** [comment]
OK, I’ll add it to Trobleshooting page
