### ISSUE TITLE
Livestyle lists empty.

### ISSUE THREAD

**Issue by wuxingtao** [livestyle/issues#76]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by sergeche** [comment]
http://livestyle.io/docs/troubleshooting/#empty-list-of-stylesheets

**Comment by wuxingtao** [comment]
i have tried  livestyle app. Confirm the installation of Emmet liveStyle 
error with :Unable to find Sublime Text installation folder. If you’re using portable version, try to install it manually.

**Comment by wuxingtao** [comment]
![2](https://cloud.githubusercontent.com/assets/4816582/12032070/0b929e02-ae4f-11e5-8368-ca59a53bbe66.png)

**Comment by sergeche** [comment]
As it says, it can’t find Sublime Text installation folder for some reason, most likely because you’re using portable version or installed ST into non-default location.

But there’s an option to install plugin manually in ST

**Comment by wuxingtao** [comment]
I using portable version,now i can find add css stylesheets.but the app Still display error。
![qq 20151229185904](https://cloud.githubusercontent.com/assets/4816582/12033507/ba35e504-ae5e-11e5-8fa3-5667f7255e3d.png)

Plus, how to use my scss stylesheet,
set syntax to SCSS?

**Comment by sergeche** [comment]
> but the app Still display error

It’s not a problem, it simply tells you why it can’t install plugin. It doesn’t affect LiveStyle at all

> Plus, how to use my scss stylesheet, set syntax to SCSS?

yes, you have to set your file syntax to SCSS in editor, they will appear in dropdowns
