### ISSUE TITLE
Не совсем рабочее обновление

### ISSUE THREAD

**Issue by code-yo** [livestyle/issues#77]
I am used old version of livestyle with sublimetext 3(all files load from wordpress), and it's was OK.

But, after updates was OK only design and i think that all, that you improve.  
Everytime, i reset my browser, and try to write some rules, but no changes are made in my files, in sublime.

Please fix your new version.

**Comment by sergeche** [comment]
I can’t understand what’s the problem. Please describe step-by-step, with screenshots: 
1. What you do
2. What you see
3. What you expect to see.

**Comment by sergeche** [comment]
Also check out Troubleshooting page with common problems and solutions: http://livestyle.io/docs/troubleshooting/

**Comment by code-yo** [comment]
Я использую расширение в связке с саблаймом. Рабоаю с вордпресом. 
Проблема заключается в том что постоянно отключается синхронизация браузера с редактором.

В плагине - все говорит о том, что связь есть, все работает, файлы даже выбраны правильные. Но при введение данных в инспекторе или наоборот в редакторе - они не синхронизируются между собой. 

Возможно проблема в том что вордпрес выгружает слишком много цсс и ваш плагин не справляется, я не знаю. Но факт в том, что работала лучше старая версия.

**Comment by sergeche** [comment]
А в логах есть какая-нибудь информация? Можете показать пример лога? Как его получить написано в http://livestyle.io/docs/troubleshooting/

**Comment by sergeche** [comment]
Как вариант, я могу подключиться к вам через TeamViewer и посмотреть, в чём именно проблема

**Comment by code-yo** [comment]
К сожалению я не смогу предоставить доступ к рабочему Пк, это нарушает регламент компании.
Вот несколько скринов: https://yadi.sk/i/oGP1OLfBmZzZ7
https://yadi.sk/i/VFg9qoUcmZzhG

В логах пусто.

Наблюдается следующее... если перезагрузить браузер и саблайм и настроить синхронизацию заново - то некоторое время все работает. После нескольких раз перезагрузки страницы, работать перестает.

Еще одно. Похоже что плагин создает кешированный дубль файла и синхронизирует его с редактором.

**Comment by sergeche** [comment]
Странно, выглядит всё нормально. Я так понимаю, работаете с удалённым сервером? Проверьте следующее:
1. Посмотрите лог в `background.html` (описано в http://livestyle.io/docs/troubleshooting/ как его увидеть), по возможности скиньте его мне
2. С WP раньше были жалобы, что теряются связи, и это было связано с тем, что URL у css-файлов менялся после перезагрузки страницы. Может, у вас такое же?
3. Ещё могут быть проблемы если есть какие-нибудь другие расширения, которые меняют данные на странице. По возможности попробуйте отключить все расширения и проверить, проявляется ли проблема.

> Похоже что плагин создает кешированный дубль файла и синхронизирует его с редактором.

Да, есть такой момент, используется для определения, в какую сторону применять обновления. Вы самостоятельно меняете файлы во вкладке Sources? По идее такие вещи должны обрабатываться, но, возможно, где-то есть проблемы с этим.

И если есть возможность как-то публично посмотреть на сайт, с которым у вас проблемы — скиньте мне ссылку на него, я сам попробую проверить

**Comment by code-yo** [comment]
Проблема похоже в размере ЦСС файлов, у ВП в рамках фреймфорка с которым я работаю - фалй style.css 6к строк и видно что плагину тяжело работать с такой бородой. 
Тестировал на файле в 900 строк - все вроде работает, к тому же сам подтягивается во вкладке sources.

https://yadi.sk/d/nze4BuN5maPxg - логи

Вы самостоятельно меняете файлы во вкладке Sources? По идее такие вещи должны обрабатываться, но, возможно, где-то есть проблемы с этим.
 -- Да, если файл большой - то приходится руками.

И если есть возможность как-то публично посмотреть на сайт, с которым у вас проблемы — скиньте мне ссылку на него, я сам попробую проверить
--К сожалению к сайту доступ только по вайт-листу и я его не определяю.

**Comment by sergeche** [comment]
Понял. Попробую как-то оптимизировать работу с большими CSS.
На всякий случай: если не нужно работать в режиме браузер→редактор, то можно закрыть DevTools, должно работать быстрее.

**Comment by code-yo** [comment]
Ок, будем ждать апдейтов.
В целом вещь очень нужная и даже вызывает зависимость.

**Comment by sergeche** [comment]
> В целом вещь очень нужная и даже вызывает зависимость.

На то и расчёт :wink: 

Если этот файл в 6k строк не секретный, можете скинуть его на мне почту serge.che@gmail.com, буду на нём производительность замерять
