### ISSUE TITLE
проблемы после обновления

### ISSUE THREAD

**Issue by Anserone** [livestyle/issues#80]
после обновления перестал работать плагин.
скачал приложение, при запуске на macos 10.11.2 при первом запуске приложение появляется в меню и мгновенно исчезает. (как логи посмотреть незнаю)
в sublime text не увидел обновление плагина, решил перезалить файлы из предложенного архива + перезагрузил, приложение в хроме обновилось, но результата не было.
пробовал с чистого листа, удалял и редактор и браузер, перезагрузил систему, приложение не запустилось(
скрин из хрома
![image](https://cloud.githubusercontent.com/assets/9901135/12035644/9fc7269c-ae4f-11e5-9051-36de87880e13.png)
консоль sublime
![2015-12-29 17 05 08](https://cloud.githubusercontent.com/assets/9901135/12035670/d68fea10-ae4f-11e5-8bd7-f924682ee787.png)

![2015-12-29 17 04 25](https://cloud.githubusercontent.com/assets/9901135/12035682/e689772e-ae4f-11e5-8efe-45c06ff551e1.png)

![2015-12-29 17 04 04](https://cloud.githubusercontent.com/assets/9901135/12035690/f04168ee-ae4f-11e5-81bf-4d7860b9c9f2.png)

не увидел в Package Control
![2015-12-29 16 58 07](https://cloud.githubusercontent.com/assets/9901135/12035703/05af9f16-ae50-11e5-97fc-d73e36db4e09.png)

ну и собственно в хроме
![2015-12-29 17 18 46](https://cloud.githubusercontent.com/assets/9901135/12035735/5d39da30-ae50-11e5-8a4d-b0cfc10f13f1.png)

**Comment by sergeche** [comment]
> скачал приложение, при запуске на macos 10.11.2 при первом запуске приложение появляется в меню и мгновенно исчезает

И нет иконки приложения на верхней панели рядом с часами? Если что, логи можно посмотреть в приложении Console, поискать там что-нибудь по слову LiveStyle.

А вообще эта ошибка означает, что используется старый плагин в Sublime Text. Обычно лечится перезапуском ST, в этот момент Package Control начинает проверять наличие обновления у плагинов. Попробуйте удалить LiveStyle из ST (обязательно через Package Control, через команду `Remove Package`) и поставить его заново

**Comment by Anserone** [comment]
ок попробую. по поводу иконки, у меня цветовая тема темная, иконку не увидел((
![2015-12-29 17 29 48](https://cloud.githubusercontent.com/assets/9901135/12035908/0ff5c872-ae52-11e5-9db4-9d1e0ca20ef1.png)

**Comment by sergeche** [comment]
Хм, не подумал об этом... Попробую что-нибудь сделать с этим.

И если что, в приложении также проверяется статус установки свежего плагина для ST, оно же должно попробовать обновить его

**Comment by Anserone** [comment]
все заработало! спасибо, кстати сколько не пытался тыкнуть в крестик все без результата
![2015-12-29 17 40 30](https://cloud.githubusercontent.com/assets/9901135/12036043/6edf36f6-ae53-11e5-8fc8-bd285e9eaae8.png)

**Comment by sergeche** [comment]
А можете открыть приложение Console и проверить, есть ли сообщения об ошибках, связанных с LiveStyle?

**Comment by Anserone** [comment]
вот как то так
![2015-12-29 17 53 24](https://cloud.githubusercontent.com/assets/9901135/12036239/3b3b5b52-ae55-11e5-8033-55780344b8b7.png)

**Comment by sergeche** [comment]
Как-то странно всё. Попробуйте перезапустить приложение (убить его в Activity Monitor), всё равно висит `Checking status`? Ещё можно кликнуть по окошку с приложением и нажать F12: откроется DevTools, в котором могут содержаться ошибки приложения

**Comment by Anserone** [comment]
перезапустил все ок, по f12 не сохранился скрин(( что-то было про maximum call stack
но все работало отлично, изменения в хроме писались в файл стилей и наоборот.
- крестик работает после перезагрузки. наверно проблемы были  из-за того, что я заменил пакет новым sublime-text-master.zip а не через sublime, ну и не увидел иконку приложения

**Comment by sergeche** [comment]
Хорошо, тогда если ещё будут подобные проблемы с приложением, напишите, пожалуйста, в отдельный issue вместе со скриншотом ошибки.
