### ISSUE TITLE
windows OS different account

### ISSUE THREAD

**Issue by lionelgmc** [livestyle/issues#84]
on other new MS OS account  no problem all work like a breeze . With my current OS user login name I don't succeed ( already have issue with it not related to chrome/emmet live ) . I have many other plugin like emmet live : prepro,  browserify , fb fo .... I don't know if the emmet live application is ableto verify that  chrome extension is install . 
I don't know if i need to be connect to google account when using chrome. What i understand is that i have 2 level of ACL : one when connect to Microosft OS and a second when launch chrome OS ( even i can be anonymous) . I install sublime extension manually using the OS user account that work . 
![emmet 19](https://cloud.githubusercontent.com/assets/4058603/12053161/997ce9f8-af16-11e5-8cd3-3d69aab53ac3.jpg)

![emmet 17](https://cloud.githubusercontent.com/assets/4058603/12053061/9175a840-af15-11e5-9902-5bd735322c27.jpg)

Ui use currPorts tool bundle with easyph pto test available port 
![emmet 18](https://cloud.githubusercontent.com/assets/4058603/12053125/23087f44-af16-11e5-90ef-30b97bc3a155.jpg)

I have update the capture screen sorry !! 
the Here my versions
--Os  windows 7 
--sublime 2 and 3  ( 2 work but no information about specific emmet plug in for ST2 or ST3 ) 
---chrome Version 49.0.2607.0 canary (64-bit)

**Comment by sergeche** [comment]
From your screenshot I can see you have outdated extension for Chrome. The most recent version is 1.0.4
You should update it as well

**Comment by lionelgmc** [comment]
i have update my post the version is ok

**Comment by sergeche** [comment]
From these screenshots everything seems fine. Make sure you have most recent version of Sublime Text plugin installed. There are many reports about ST plugin not being updated correctly. Try to remove ST plugin and install again

**Comment by lionelgmc** [comment]
i think it is ST issue but  i don't know 
if the emmet plugin work for old and last ST version ? 
if i can install and use ST 2 and ST3  in same time wit hemmet ? 
if i have to remove one ST version ( the old one )  ? 
i think i have to test all case !! 

regard's

**Comment by sergeche** [comment]
Yes, you can use both ST2 and ST3. The LiveStyle app should update installed plugins automatically. What app displays to you?

The easiest way to check if you have outdated ST package is to open ST console, if there are number of `WARNING:tornado.access:404 GET /livestyle (127.0.0.1)` messages then it definitely outdated ST plugin. If you installed it via Package Control, simply run Remove Package command and then Install Package again

**Comment by lionelgmc** [comment]
I discover ST because is the only "IDE" text editor compatible with emmet until now when read the documentation . 
what do you mean by ST console ? launch  ST using CLI ?  or there is a menu to launch a console from ST ?  OK : View -show console 

![emmet 11](https://cloud.githubusercontent.com/assets/4058603/12053345/6fdf4364-af18-11e5-927e-b789ab5a7e09.jpg)
I don't succed to have when using the emmet app the information "installed" for chrome in the same way emmet application show me in the right side that emmet plug in is intalled for Sublime ! 
install chrome application could be automate using emmet application even the installation is under the control of chrome ?? !!!! chrome API return information about succeed installation of plugin ?

**Comment by lionelgmc** [comment]
LiveStyle: ['Traceback (most recent call last):\n', '  File "C:\\Users\\lionel\\AppData\\Roaming\\Sublime Text 2\\Packages\\LiveStyle\\tornado.zip\\tornado\\gen.py", line 1014, in run\n', '  File ".\\livestyle-plugin.py", line 182, in client_connect\n    create_server(port)\n', '  File ".\\livestyle-plugin.py", line 190, in create_server\n    server.start(port=port)\n', '  File ".\\livestyle\\server.py", line 160, in start\n    httpserver.listen(port, address=address)\n', '  File "C:\\Users\\lionel\\AppData\\Roaming\\Sublime Text 2\\Packages\\LiveStyle\\tornado.zip\\tornado\\tcpserver.py", line 126, in listen\n', '  File "C:\\Users\\lionel\\AppData\\Roaming\\Sublime Text 2\\Packages\\LiveStyle\\tornado.zip\\tornado\\netutil.py", line 196, in bind_sockets\n', '  File "<string>", line 1, in bind\n', 'error: [Errno 10048] Une seule utilisation de chaque adresse de socket (protocole/adresse r\xe9seau/port) est habituellement autoris\xe9e\n']
error: Unable to create to LiveStyle server. Make sure your firewall/proxy does not block 54000 port
Package Control: Settings change detected, clearing cache

**Comment by lionelgmc** [comment]
LiveStyle: ['Traceback (most recent call last):\n', '  File "C:\\Users\\lionel\\AppData\\Roaming\\Sublime Text 2\\Packages\\LiveStyle\\tornado.zip\\tornado\\gen.py", line 1014, in run\n', '  File ".\\livestyle-plugin.py", line 182, in client_connect\n    create_server(port)\n', '  File ".\\livestyle-plugin.py", line 190, in create_server\n    server.start(port=port)\n', '  File ".\\livestyle\\server.py", line 160, in start\n    httpserver.listen(port, address=address)\n', '  File "C:\\Users\\lionel\\AppData\\Roaming\\Sublime Text 2\\Packages\\LiveStyle\\tornado.zip\\tornado\\tcpserver.py", line 126, in listen\n', '  File "C:\\Users\\lionel\\AppData\\Roaming\\Sublime Text 2\\Packages\\LiveStyle\\tornado.zip\\tornado\\netutil.py", line 196, in bind_sockets\n', '  File "<string>", line 1, in bind\n', 'error: [Errno 10048] Une seule utilisation de chaque adresse de socket (protocole/adresse r\xe9seau/port) est habituellement autoris\xe9e\n']
error: Unable to create to LiveStyle server. Make sure your firewall/proxy does not block 54000 port
Package Control: Settings change detected, clearing cache

**Comment by lionelgmc** [comment]
it seem i use 2 OS account that use the same port i have to verify that 
thanks i ll test and post back !!

**Comment by lionelgmc** [comment]
Ok all see mto be resolve 
![emmet_manyport](https://cloud.githubusercontent.com/assets/4058603/12053522/5b098132-af1a-11e5-86fc-005101c2dfbc.png)
