### ISSUE TITLE
OSX menu bar icon doesn't show up on Dark Mode

### ISSUE THREAD

**Issue by altern8tif** [livestyle/issues#87]
The Livestyle menu bar icon is black, which means it doesn't show up on the OS X's Dark Mode version.

![screen shot 2016-01-01 at 11 09 09 am](https://cloud.githubusercontent.com/assets/5793364/12069638/3e3b9c34-b078-11e5-88ee-079ebb694edf.png)
(Screenshot when clicking on menu bar icon)

**Comment by sergeche** [comment]
Please re-download app, it should contain fixed menu icon that works in dark theme as well

**Comment by altern8tif** [comment]
:+1:
