### ISSUE TITLE
Detected as a malware on windows 10

### ISSUE THREAD

**Issue by AlaNDGT** [livestyle/issues#88]
Livestylesetup.exe
Version: 1.0.0.0
It's detected as a malware on Windows 10
![capture](https://cloud.githubusercontent.com/assets/3120817/12070407/c9418e60-b08c-11e5-9f5f-43d342fa85eb.PNG)

**Comment by sergeche** [comment]
I’ve tried to google about it: it’s mostly a default behaviour of Windows SmartScreen protection for files recently available in the internet.

The app itself is just a JS, HTML & CSS with default [Electron](http://electron.atom.io) and [Squirrel](https://github.com/Squirrel/Squirrel.Windows) installer

**Comment by AlaNDGT** [comment]
ohh okay, thanks for the reply (and info)! :-)
