### ISSUE TITLE
can't create new selector only modify 

### ISSUE THREAD

**Issue by lionelgmc** [livestyle/issues#91]
Hi 
i test sublime Text ( ST) and chrome (C )  . I can from chrome  create new selector but no update in the OS file system  and in ST. If i create the selector in ST and save then nothing to do on chrome :  the selector appear in chrome and then i can create new css properties ( attribut valeu) !! 
Is it the default behaviour of emmet live style ? Does this ll be change is a feature roadmap ? Does i miss something !! 

Do you know ( i know already some tools ....) 
a) a real html editor  for chrome debug ? 
b) the best way to reload the modify html in chrome ( auto update like emmet do for css ) 

Is there ll be a plugin for the most use IDE : BBwrangler , aptana , phpstorm , bracket  ?  

regard's 

sublime text 2.0.2 build 2221  with emmet plugin 
chrome  canary 49.0.2610.0 with ememt plug in and workspace

**Comment by sergeche** [comment]
Not sure if I understood you correctly... You’ve created selector in Chrome DevTools and it doesn’t appear in editor? I seems like you’ve created selector in inspector stylesheet, not the file you associated with text editor

**Comment by sergeche** [comment]
As for other questions: no, I don’t know about HTML edit tools and LiveStyle is currently available for Sublime Text and Atom

**Comment by lionelgmc** [comment]
Yes i open ST and then chrome for go to local url ( http://)  and open the chrome developer Tools then i open 2 "windows" in the chrome developper : in the left  the DOM tree ( not the tree source html code file ) and in the left the Styles panel . I select in the DOM an item ( tag<body< )and go to the style panel to click on icon cross "+" ( pop up name appear label  "new style rule") then chrome  create a empty selector of name body ( body :{} nb no attribut inside body tag ) even a body selector exist add by browser "reset" . After i add css properties in the body seelctor , nothing occur in the Sublime text editor . If i create the empty body selector in ST and edit it in chrome then the css properties edit in chrome appear in ST . 

thank's for the name of supported  editor , i ll test it after find the emmet plugin for atom !!

**Comment by sergeche** [comment]
When you click on a `+` button, you create selector in separate stylesheet (called “Inspector stylesheet”), which is not available for association with editor file. 

The LiveStyle workflow assumes that you should create all selectors in editor and use DevTools for visual layout tweaking.

**Comment by lionelgmc** [comment]
ok thank's a lot  ... Very great usefull tool ..... for designer 
regard's

**Comment by sergeche** [comment]
I’ll try to find a way how to properly map changes from inspector stylesheet into editor source code
