### ISSUE TITLE
Add stylesheet button not working and stylesheets not showing

### ISSUE THREAD

**Issue by sri429** [livestyle/issues#93]
I am running a static html page in chrome. 
In this case the stylesheets included in the page are not shown.
Also the add style sheet button is also not working. clicking on it doesn't do anything.

But works for my localhost, and other websites where a web server is involved.

**Comment by sri429** [comment]
I am seeing in this on Mac OS X el capitan. chrome latest/canary latest

**Comment by sergeche** [comment]
Can you post a screenshot of your web page of your Chrome browser with opened LiveStyle popup and source code of your page?

**Comment by BenCrab** [comment]
I'm also experiencing the same issue, except I'm on OS X Yosemite.

![screen shot 2016-01-06 at 9 06 19 am](https://cloud.githubusercontent.com/assets/5695667/12147292/646955fa-b455-11e5-91a9-c5b0cfe695ca.png)
![image](https://cloud.githubusercontent.com/assets/5695667/12147323/8bdbc6d6-b455-11e5-9b1d-05e05a610665.png)

**Comment by sergeche** [comment]
@BenCrab most likely it caused by automatic extension update. Try to close DevTools (if opened), refresh page and check again

**Comment by BenCrab** [comment]
@sergeche That worked! Thanks
