### ISSUE TITLE
send socket message :  request-unsaved-changes

### ISSUE THREAD

**Issue by eissasoubhi** [livestyle/issues#95]
Hi

somtimes LS doesn't apply changes and show this message in the LS console **"send socket message :  request-unsaved-changes"**.

i solve this by reinstalling  it .

is there any better solution ?

Thank U

**Comment by sergeche** [comment]
The `request-unsaved-changes` message is sent when you reload web-page. It asks for unsaved changes in editor files so you can continue with where you left after page reload. It has nothing to do with changes not being applied when you edit source code.

Possible reasons are: invalid source code (LiveStyle is sensitive to code), you didn’t connect required files, or maybe some other tool rewrites CSS in browser

**Comment by eissasoubhi** [comment]
ok, i'll check that next time, thanks for the reply.
