### ISSUE TITLE
Use Event Page instead of background.js on the Chrome Extension

### ISSUE THREAD

**Issue by franciscolourenco** [livestyle/issues#97]
The background page doesn't need to be running all the time and consuming resources specially when the extension is not being used in any page.

https://developer.chrome.com/extensions/event_pages

**Comment by sergeche** [comment]
LiveStyle caches previously calculated stylesheets contents and dependencies for faster diffing. If these caches will be unexpectedly unloaded by browser, it will introduce performance degradation and bugs

**Comment by franciscolourenco** [comment]
Can't these caches be saved with [chrome.storage](https://developer.chrome.com/extensions/storage) or IndexedDB?

**Comment by sergeche** [comment]
Maybe. Right now they are used and stored in background Worker process so it’s not that easy to them into something that specific to environment

**Comment by sergeche** [comment]
LiveStyle isn’t optimized for hight performance and efficiency yet so there’s a lot work to do. If it get enough attention and user base, I’ll continue its further improvements

**Comment by sergeche** [comment]
Event page is not an option because LiveStyle requires persistent Websocket connection with editor
